In [3]:
# I dont have enough space to process all at once
songs_folder = "/home/saliherdemk/osu-songs"

In [4]:
import os
import shutil
from tqdm import tqdm

def split_into_subfolders(folder_path, batch_size=500):
    all_files = os.listdir(folder_path)
    chunks = [all_files[i: i + batch_size] for i in range(0, len(all_files), batch_size)]
    for idx, chunk in tqdm(enumerate(chunks), total=len(chunks)):
        desc_folder = f"/home/saliherdemk/osu-chunks/{idx}"
        os.makedirs(desc_folder, exist_ok=True)
        for f in chunk:
            source = os.path.join(songs_folder,f)
            destination = os.path.join(desc_folder,f)
            shutil.move(source, destination)

In [5]:
split_into_subfolders(songs_folder, batch_size=1000)

100%|████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 32.61it/s]

In [17]:
import requests
CLIENT_ID=36927
CLIENT_SECRET="cKtCGYRDhHmxjprCTlQKBmOahapcDL8G6A5fheIY"

def get_access_token():
    url = "https://osu.ppy.sh/oauth/token"
    headers = {"Content-Type": "application/x-www-form-urlencoded"}
    data = {
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
        "grant_type": "client_credentials",
        "scope": "public",
    }

    response = requests.post(url, headers=headers, data=data)
    return response.json().get("access_token")

In [18]:
def get_beatmapset_metadata(beatmapset_id, access_token):
    url = f"https://osu.ppy.sh/api/v2/beatmapsets/{beatmapset_id}"
    headers = {"Authorization": f"Bearer {access_token}", "Accept": "application/json"}

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        beatmapset = response.json()
        ranked_date = beatmapset.get("ranked_date", None)
        status = beatmapset.get("status", None)
        mapper_id = beatmapset.get("user_id", None)
        beatmaps = {}
        for beatmap in beatmapset.get("beatmaps"):
            beatmaps[beatmap["version"]] = beatmap["difficulty_rating"]
        print(beatmaps)

In [19]:
access_token = get_access_token()

In [20]:
get_beatmapset_metadata(2412247, access_token)

{'BEGINNER': 1.74, 'LEGGENDARIA': 6.61, 'HYPER': 3.72, 'ANOTHER': 5.07, 'NOVICE': 2.5, "KVNMS's EXPERT": 6.01}

In [10]:
import pandas as pd

df1 = pd.read_csv("/home/saliherdemk/try_dataset/formatted/formatted_old.csv")
df2 = pd.read_csv("/home/saliherdemk/try_dataset/formatted/formatted.csv")
df1_sorted = df1.sort_values(by=list(df1.columns)).reset_index(drop=True)
df2_sorted = df2.sort_values(by=list(df2.columns)).reset_index(drop=True)

print(df1_sorted.equals(df2_sorted))

False

In [8]:
df1_sorted

,id,time,type,x,y,hit_sound,path,repeat,spinner_time,new_combo,...,sample_set,volume,effects,difficulty_rating,meter,beat_length,mapper_id,beatmap_id,duration,delta_time
0,14309-0,295.0,circle,376,192,4,E|,0,0,False,...,1,60,0,5.22,4,352.941176,250808,14309,0,0
1,14309-0,647.0,slider,256,340,0,B|200:356|164:296,2,0,False,...,1,60,0,5.22,4,352.941176,250808,14309,176,352
2,14309-0,1353.0,circle,196,160,8,E|,0,0,False,...,1,60,0,5.22,4,352.941176,250808,14309,0,706
3,14309-0,1706.0,slider,340,272,0,B|376:256|400:292|440:272,1,0,True,...,1,60,0,5.22,4,352.941176,250808,14309,176,353
4,14309-0,2236.0,slider,172,112,0,B|136:128|112:92|72:112,1,0,False,...,1,60,0,5.22,4,352.941176,250808,14309,176,530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53797,42909-3,133047.0,slider,336,136,0,B|296:176,1,0,False,...,1,80,1,2.53,4,315.789474,537084,42909,157,316
53798,42909-3,133363.0,slider,256,176,0,B|216:216,1,0,False,...,1,80,1,2.53,4,315.789474,537084,42909,157,316
53799,42909-3,133678.0,circle,184,240,8,E|,0,0,False,...,1,80,1,2.53,4,315.789474,537084,42909,0,315
53800,42909-3,133836.0,circle,160,272,8,E|,0,0,False,...,1,80,1,2.53,4,315.789474,537084,42909,0,158
53801,42909-3,133994.0,circle,160,312,4,E|,0,0,False,...,2,80,0,2.53,4,315.789474,537084,42909,0,158

In [9]:
df2_sorted

,id,time,type,x,y,hit_sound,path,repeat,spinner_time,new_combo,...,sample_set,volume,effects,difficulty_rating,meter,beat_length,mapper_id,beatmap_id,duration,delta_time
0,14309-0,295.0,circle,376,192,4,E|,0,0,False,...,1,60,0,5.22,4,352.941176,250808,14309,0,0
1,14309-0,647.0,slider,256,340,0,B|200:356|164:296,2,0,False,...,1,60,0,5.22,4,352.941176,250808,14309,176,352
2,14309-0,1353.0,circle,196,160,8,E|,0,0,False,...,1,60,0,5.22,4,352.941176,250808,14309,0,706
3,14309-0,1706.0,slider,340,272,0,B|376:256|400:292|440:272,1,0,True,...,1,60,0,5.22,4,352.941176,250808,14309,176,353
4,14309-0,2236.0,slider,172,112,0,B|136:128|112:92|72:112,1,0,False,...,1,60,0,5.22,4,352.941176,250808,14309,176,530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53797,42909-3,133047.0,slider,336,136,0,B|296:176,1,0,False,...,1,60,1,2.53,4,315.789474,537084,42909,157,316
53798,42909-3,133363.0,slider,256,176,0,B|216:216,1,0,False,...,1,60,1,2.53,4,315.789474,537084,42909,157,316
53799,42909-3,133678.0,circle,184,240,8,E|,0,0,False,...,1,60,1,2.53,4,315.789474,537084,42909,0,315
53800,42909-3,133836.0,circle,160,272,8,E|,0,0,False,...,1,60,1,2.53,4,315.789474,537084,42909,0,158
53801,42909-3,133994.0,circle,160,312,4,E|,0,0,False,...,2,80,0,2.53,4,315.789474,537084,42909,0,158