# Dataset

In [19]:
import torch
from torch.utils.data import Dataset
import librosa
import numpy as np
from transformers import AutoProcessor, AutoModel
import os

class MERTChunkDataset(Dataset):
    def __init__(self, audio_folder, chunk_length_sec=10.0, overlap_sec=5.0, target_sr=24000, device='cpu'):
        self.audio_folder = audio_folder
        self.chunk_length_sec = chunk_length_sec
        self.overlap_sec = overlap_sec
        self.chunk_stride = chunk_length_sec - overlap_sec
        self.target_sr = target_sr
        self.device = device

        self.processor = AutoProcessor.from_pretrained("m-a-p/MERT-v1-95M", trust_remote_code=True)
        self.model = AutoModel.from_pretrained("m-a-p/MERT-v1-95M", trust_remote_code=True)
        self.model.eval()
        self.model.to(device)

        self.data = []
        for path in os.listdir(audio_folder):
            self.data.extend(self._process_file(os.path.join(audio_folder, path)))

    def _process_file(self, path):
        y, sr = librosa.load(path, sr=self.target_sr)
        total_sec = y.shape[0] / sr
        chunk_starts = np.arange(0, total_sec, self.chunk_stride)
        file_chunks = []

        for start_sec in chunk_starts:
            end_sec = start_sec + self.chunk_length_sec
            start_sample = int(start_sec * sr)
            end_sample = int(end_sec * sr)
            chunk_audio = y[start_sample:end_sample].astype(np.float32)
            if len(chunk_audio) == 0:
                continue

            inputs = self.processor(raw_speech=chunk_audio, sampling_rate=sr, return_tensors="pt").to(self.device)
            with torch.no_grad():
                embeddings = self.model(**inputs).last_hidden_state.squeeze(0)

            file_chunks.append(embeddings.cpu())
        return file_chunks

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

In [20]:
dataset = MERTChunkDataset("/home/saliherdemk/try_dataset/audio/", chunk_length_sec=10.0, overlap_sec=5.0, target_sr=24000, device='cpu')

print("Number of chunks:", len(dataset))
print("Shape of first chunk:", dataset[0].shape)

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

KeyboardInterrupt:

In [22]:
import os
import torch
import librosa
import numpy as np
from transformers import AutoProcessor, AutoModel
import json
from tqdm import tqdm

audio_folder = "/home/saliherdemk/try_dataset/audio/"
embedding_folder = "/home/saliherdemk/try_dataset//embeddings"
chunk_length_sec = 10.0
overlap_sec = 5.0
target_sr = 24000
device = "cuda" if torch.cuda.is_available() else "cpu"

os.makedirs(embedding_folder, exist_ok=True)

processor = AutoProcessor.from_pretrained("m-a-p/MERT-v1-95M", trust_remote_code=True)
model = AutoModel.from_pretrained("m-a-p/MERT-v1-95M", trust_remote_code=True)
model.eval()
model.to(device)

audio_files = [f for f in os.listdir(audio_folder))]

for audio_file in tqdm(audio_files, desc="Processing audio"):
    audio_path = os.path.join(audio_folder, audio_file)
    beatmap_id = os.path.splitext(audio_file)[0]

    y, sr = librosa.load(audio_path, sr=target_sr)
    total_sec = y.shape[0] / sr
    chunk_stride = chunk_length_sec - overlap_sec
    chunk_starts = np.arange(0, total_sec, chunk_stride)

    for chunk_idx, start_sec in enumerate(chunk_starts):
        end_sec = start_sec + chunk_length_sec
        start_sample = int(start_sec * sr)
        end_sample = int(end_sec * sr)
        chunk_audio = y[start_sample:end_sample].astype(np.float32)
        if len(chunk_audio) == 0:
            continue

        inputs = processor(raw_speech=chunk_audio, sampling_rate=sr, return_tensors="pt").to(device)
        with torch.no_grad():
            embeddings = model(**inputs).last_hidden_state.squeeze(0).cpu()

        save_name = f"{beatmap_id}_chunk{chunk_idx}.pt"
        save_path = os.path.join(embedding_folder, save_name)
        torch.save(embeddings, save_path)

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Processing audio:   2%|██▉                                                                                                                                                          | 1/54 [00:25<22:42, 25.71s/it]

KeyboardInterrupt:

In [25]:
import pandas as pd

df = pd.read_csv("/home/saliherdemk/try_dataset/formatted.csv")

In [28]:
import pandas as pd
import numpy as np

chunk_length_sec = 10
overlap_sec = 5
chunk_length_ms = chunk_length_sec * 1000
chunk_stride_ms = (chunk_length_sec - overlap_sec) * 1000

def get_chunks_for_hit(hit_start_ms, duration_ms, chunk_length_ms, chunk_stride_ms):
    hit_end_ms = hit_start_ms + duration_ms
    chunk_starts = np.arange(0, hit_end_ms + chunk_stride_ms, chunk_stride_ms)
    chunk_ids = []
    for i, chunk_start in enumerate(chunk_starts):
        chunk_end = chunk_start + chunk_length_ms
        if hit_end_ms > chunk_start and hit_start_ms < chunk_end:
            chunk_ids.append(i)
    return chunk_ids

df["chunk_id"] = df.apply(lambda row: get_chunks_for_hit(row["time"], row["duration"], chunk_length_ms, chunk_stride_ms), axis=1)

df[df["id"] == "14309-0"].head(20)

,id,time,type,x,y,hit_sound,path,repeat,spinner_time,new_combo,...,volume,effects,difficulty_rating,meter,beat_length,mapper_id,beatmap_id,duration,delta_time,chunk_id
0,14309-0,295.0,circle,376,192,4,E|,0,0,False,...,60,0,5.22,4,352.941176,250808,14309,0,295,[0]
1,14309-0,647.0,slider,256,340,0,B|200:356|164:296,2,0,False,...,60,0,5.22,4,352.941176,250808,14309,176,352,[0]
2,14309-0,1353.0,circle,196,160,8,E|,0,0,False,...,60,0,5.22,4,352.941176,250808,14309,0,706,[0]
3,14309-0,1706.0,slider,340,272,0,B|376:256|400:292|440:272,1,0,True,...,60,0,5.22,4,352.941176,250808,14309,176,353,[0]
4,14309-0,2236.0,slider,172,112,0,B|136:128|112:92|72:112,1,0,False,...,60,0,5.22,4,352.941176,250808,14309,176,530,[0]
5,14309-0,2765.0,circle,256,192,8,E|,0,0,False,...,60,0,5.22,4,352.941176,250808,14309,0,529,[0]
6,14309-0,3118.0,circle,136,192,4,E|,0,0,True,...,60,0,5.22,4,352.941176,250808,14309,0,353,[0]
7,14309-0,3470.0,slider,256,44,0,B|312:28|348:88,2,0,False,...,60,0,5.22,4,352.941176,250808,14309,176,352,[0]
8,14309-0,4176.0,circle,316,224,8,E|,0,0,False,...,60,0,5.22,4,352.941176,250808,14309,0,706,[0]
9,14309-0,4353.0,circle,196,224,0,E|,0,0,False,...,60,0,5.22,4,352.941176,250808,14309,0,177,[0]
10,14309-0,4530.0,slider,256,120,0,B|256:216,1,0,False,...,60,0,5.22,4,352.941176,250808,14309,176,177,[0]
11,14309-0,5059.0,circle,80,340,0,E|,0,0,True,...,60,0,5.22,4,352.941176,250808,14309,0,529,"[0, 1]"
12,14309-0,5236.0,circle,152,284,8,E|,0,0,False,...,60,0,5.22,4,352.941176,250808,14309,0,177,"[0, 1]"
13,14309-0,5412.0,circle,64,252,0,E|,0,0,False,...,60,0,5.22,4,352.941176,250808,14309,0,176,"[0, 1]"
14,14309-0,5589.0,circle,136,192,8,E|,0,0,False,...,60,0,5.22,4,352.941176,250808,14309,0,177,"[0, 1]"
15,14309-0,5677.0,circle,136,192,0,E|,0,0,False,...,60,0,5.22,4,352.941176,250808,14309,0,88,"[0, 1]"
16,14309-0,5765.0,circle,136,192,0,E|,0,0,False,...,60,0,5.22,4,352.941176,250808,14309,0,88,"[0, 1]"
17,14309-0,5853.0,circle,136,192,0,E|,0,0,False,...,60,0,5.22,4,352.941176,250808,14309,0,88,"[0, 1]"
18,14309-0,5942.0,circle,136,192,4,E|,0,0,True,...,60,0,5.22,4,352.941176,250808,14309,0,89,"[0, 1]"
19,14309-0,6294.0,slider,256,44,0,B|312:28|348:88,2,0,False,...,60,0,5.22,4,352.941176,250808,14309,176,352,"[0, 1]"

In [35]:
df_exploded = df.explode("chunk_id").reset_index(drop=True)

chunk_length_sec = 10
overlap_sec = 5
chunk_stride_sec = chunk_length_sec - overlap_sec
df_exploded['chunk_start'] = df_exploded['chunk_id'] * chunk_stride_sec * 1000
df_exploded['hit_start_rel'] = df_exploded['time'] - df_exploded['chunk_start']
df_exploded['hit_end_rel'] = df_exploded['hit_start_rel'] + df_exploded['duration']

grouped = df_exploded.groupby('chunk_id')

chunk_dict = {}
for chunk_id, group in grouped:
    chunk_rows = group.to_dict(orient='records')
    chunk_dict[chunk_id] = chunk_rows

chunk_dict[0]

[{'id': '14309-0',
  'time': 295.0,
  'type': 'circle',
  'x': 376,
  'y': 192,
  'hit_sound': 4,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 295,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 295.0,
  'hit_end_rel': 295.0},
 {'id': '14309-0',
  'time': 647.0,
  'type': 'slider',
  'x': 256,
  'y': 340,
  'hit_sound': 0,
  'path': 'B|200:356|164:296',
  'repeat': 2,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 176,
  'delta_time': 352,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 647.0,
  'hit_end_rel': 823.0},
 {'id': '14309-0',
  'time': 1353.0,
  'type': 'circle',
  'x': 196,
  'y': 160,
  'hit_sound': 8,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 706,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 1353.0,
  'hit_end_rel': 1353.0},
 {'id': '14309-0',
  'time': 1706.0,
  'type': 'slider',
  'x': 340,
  'y': 272,
  'hit_sound': 0,
  'path': 'B|376:256|400:292|440:272',
  'repeat': 1,
  'spinner_time': 0,
  'new_combo': True,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 176,
  'delta_time': 353,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 1706.0,
  'hit_end_rel': 1882.0},
 {'id': '14309-0',
  'time': 2236.0,
  'type': 'slider',
  'x': 172,
  'y': 112,
  'hit_sound': 0,
  'path': 'B|136:128|112:92|72:112',
  'repeat': 1,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 176,
  'delta_time': 530,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 2236.0,
  'hit_end_rel': 2412.0},
 {'id': '14309-0',
  'time': 2765.0,
  'type': 'circle',
  'x': 256,
  'y': 192,
  'hit_sound': 8,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 529,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 2765.0,
  'hit_end_rel': 2765.0},
 {'id': '14309-0',
  'time': 3118.0,
  'type': 'circle',
  'x': 136,
  'y': 192,
  'hit_sound': 4,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': True,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 353,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 3118.0,
  'hit_end_rel': 3118.0},
 {'id': '14309-0',
  'time': 3470.0,
  'type': 'slider',
  'x': 256,
  'y': 44,
  'hit_sound': 0,
  'path': 'B|312:28|348:88',
  'repeat': 2,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 176,
  'delta_time': 352,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 3470.0,
  'hit_end_rel': 3646.0},
 {'id': '14309-0',
  'time': 4176.0,
  'type': 'circle',
  'x': 316,
  'y': 224,
  'hit_sound': 8,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 706,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 4176.0,
  'hit_end_rel': 4176.0},
 {'id': '14309-0',
  'time': 4353.0,
  'type': 'circle',
  'x': 196,
  'y': 224,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 177,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 4353.0,
  'hit_end_rel': 4353.0},
 {'id': '14309-0',
  'time': 4530.0,
  'type': 'slider',
  'x': 256,
  'y': 120,
  'hit_sound': 0,
  'path': 'B|256:216',
  'repeat': 1,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 176,
  'delta_time': 177,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 4530.0,
  'hit_end_rel': 4706.0},
 {'id': '14309-0',
  'time': 5059.0,
  'type': 'circle',
  'x': 80,
  'y': 340,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': True,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 529,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 5059.0,
  'hit_end_rel': 5059.0},
 {'id': '14309-0',
  'time': 5236.0,
  'type': 'circle',
  'x': 152,
  'y': 284,
  'hit_sound': 8,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 177,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 5236.0,
  'hit_end_rel': 5236.0},
 {'id': '14309-0',
  'time': 5412.0,
  'type': 'circle',
  'x': 64,
  'y': 252,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 176,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 5412.0,
  'hit_end_rel': 5412.0},
 {'id': '14309-0',
  'time': 5589.0,
  'type': 'circle',
  'x': 136,
  'y': 192,
  'hit_sound': 8,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 177,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 5589.0,
  'hit_end_rel': 5589.0},
 {'id': '14309-0',
  'time': 5677.0,
  'type': 'circle',
  'x': 136,
  'y': 192,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 88,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 5677.0,
  'hit_end_rel': 5677.0},
 {'id': '14309-0',
  'time': 5765.0,
  'type': 'circle',
  'x': 136,
  'y': 192,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 88,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 5765.0,
  'hit_end_rel': 5765.0},
 {'id': '14309-0',
  'time': 5853.0,
  'type': 'circle',
  'x': 136,
  'y': 192,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 88,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 5853.0,
  'hit_end_rel': 5853.0},
 {'id': '14309-0',
  'time': 5942.0,
  'type': 'circle',
  'x': 136,
  'y': 192,
  'hit_sound': 4,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': True,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 89,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 5942.0,
  'hit_end_rel': 5942.0},
 {'id': '14309-0',
  'time': 6294.0,
  'type': 'slider',
  'x': 256,
  'y': 44,
  'hit_sound': 0,
  'path': 'B|312:28|348:88',
  'repeat': 2,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 176,
  'delta_time': 352,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 6294.0,
  'hit_end_rel': 6470.0},
 {'id': '14309-0',
  'time': 7000.0,
  'type': 'circle',
  'x': 316,
  'y': 224,
  'hit_sound': 8,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 706,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 7000.0,
  'hit_end_rel': 7000.0},
 {'id': '14309-0',
  'time': 7353.0,
  'type': 'slider',
  'x': 172,
  'y': 112,
  'hit_sound': 0,
  'path': 'B|136:128|112:92|72:112',
  'repeat': 1,
  'spinner_time': 0,
  'new_combo': True,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 176,
  'delta_time': 353,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 7353.0,
  'hit_end_rel': 7529.0},
 {'id': '14309-0',
  'time': 7883.0,
  'type': 'slider',
  'x': 340,
  'y': 272,
  'hit_sound': 0,
  'path': 'B|376:256|400:292|440:272',
  'repeat': 1,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 176,
  'delta_time': 530,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 7883.0,
  'hit_end_rel': 8059.0},
 {'id': '14309-0',
  'time': 8412.0,
  'type': 'circle',
  'x': 256,
  'y': 192,
  'hit_sound': 8,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 529,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 8412.0,
  'hit_end_rel': 8412.0},
 {'id': '14309-0',
  'time': 8765.0,
  'type': 'circle',
  'x': 376,
  'y': 192,
  'hit_sound': 4,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': True,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 353,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 8765.0,
  'hit_end_rel': 8765.0},
 {'id': '14309-0',
  'time': 9117.0,
  'type': 'slider',
  'x': 256,
  'y': 340,
  'hit_sound': 0,
  'path': 'B|200:356|164:296',
  'repeat': 2,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 176,
  'delta_time': 352,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 9117.0,
  'hit_end_rel': 9293.0},
 {'id': '14309-0',
  'time': 9824.0,
  'type': 'circle',
  'x': 256,
  'y': 192,
  'hit_sound': 8,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 1.9,
  'sample_set': 1,
  'volume': 60,
  'effects': 0,
  'difficulty_rating': 5.22,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 707,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 9824.0,
  'hit_end_rel': 9824.0},
 {'id': '14309-1',
  'time': 295.0,
  'type': 'slider',
  'x': 344,
  'y': 248,
  'hit_sound': 0,
  'path': 'B|328:296|256:328|184:296|168:248',
  'repeat': 1,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 352,
  'delta_time': 295,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 295.0,
  'hit_end_rel': 647.0},
 {'id': '14309-1',
  'time': 824.0,
  'type': 'slider',
  'x': 167,
  'y': 136,
  'hit_sound': 0,
  'path': 'B|184:88|256:56|328:88|344:136',
  'repeat': 1,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 352,
  'delta_time': 529,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 824.0,
  'hit_end_rel': 1176.0},
 {'id': '14309-1',
  'time': 1353.0,
  'type': 'circle',
  'x': 256,
  'y': 192,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 529,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 1353.0,
  'hit_end_rel': 1353.0},
 {'id': '14309-1',
  'time': 1706.0,
  'type': 'circle',
  'x': 464,
  'y': 256,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': True,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 353,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 1706.0,
  'hit_end_rel': 1706.0},
 {'id': '14309-1',
  'time': 1883.0,
  'type': 'circle',
  'x': 464,
  'y': 128,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 177,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 1883.0,
  'hit_end_rel': 1883.0},
 {'id': '14309-1',
  'time': 2236.0,
  'type': 'circle',
  'x': 112,
  'y': 320,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 353,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 2236.0,
  'hit_end_rel': 2236.0},
 {'id': '14309-1',
  'time': 2412.0,
  'type': 'circle',
  'x': 72,
  'y': 240,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 176,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 2412.0,
  'hit_end_rel': 2412.0},
 {'id': '14309-1',
  'time': 2589.0,
  'type': 'circle',
  'x': 72,
  'y': 144,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 177,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 2589.0,
  'hit_end_rel': 2589.0},
 {'id': '14309-1',
  'time': 2765.0,
  'type': 'circle',
  'x': 120,
  'y': 64,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 176,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 2765.0,
  'hit_end_rel': 2765.0},
 {'id': '14309-1',
  'time': 2942.0,
  'type': 'circle',
  'x': 344,
  'y': 136,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': True,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 177,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 2942.0,
  'hit_end_rel': 2942.0},
 {'id': '14309-1',
  'time': 3030.0,
  'type': 'circle',
  'x': 344,
  'y': 136,
  'hit_sound': 0,
  'path': 'E|',
  'repeat': 0,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 0,
  'delta_time': 88,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 3030.0,
  'hit_end_rel': 3030.0},
 {'id': '14309-1',
  'time': 3118.0,
  'type': 'slider',
  'x': 344,
  'y': 136,
  'hit_sound': 0,
  'path': 'B|328:88|256:56|184:88|168:136',
  'repeat': 1,
  'spinner_time': 0,
  'new_combo': False,
  'slider_velocity': 2.2,
  'sample_set': 1,
  'volume': 70,
  'effects': 0,
  'difficulty_rating': 5.91,
  'meter': 4,
  'beat_length': 352.941176470588,
  'mapper_id': 250808,
  'beatmap_id': 14309,
  'duration': 352,
  'delta_time': 88,
  'chunk_id': 0,
  'chunk_start': 0,
  'hit_start_rel': 3118.0,
  'hit_end_rel': 3470.0},
 {'id': '14309-1',
  'time': 3647.0,
  'type': 'slider',
  'x': 168,
  'y': 248,
  'hit_sound': 0,
  'path': 'B|184:296|256:328|328:296|344:248',
  'repeat': 1,
  'spinner_time': 0,

In [47]:
display(df_exploded[df_exploded["id"] == "14309-0"][["id", "time", "type", "x", "y", "duration", "delta_time", "chunk_id", "chunk_start", "hit_start_rel", "hit_end_rel"]])

           id      time     type    x    y  duration  delta_time chunk_id  \
0     14309-0     295.0   circle  376  192         0         295        0
1     14309-0     647.0   slider  256  340       176         352        0
2     14309-0    1353.0   circle  196  160         0         706        0
3     14309-0    1706.0   slider  340  272       176         353        0
4     14309-0    2236.0   slider  172  112       176         530        0
5     14309-0    2765.0   circle  256  192         0         529        0
6     14309-0    3118.0   circle  136  192         0         353        0
7     14309-0    3470.0   slider  256   44       176         352        0
8     14309-0    4176.0   circle  316  224         0         706        0
9     14309-0    4353.0   circle  196  224         0         177        0
10    14309-0    4530.0   slider  256  120       176         177        0
11    14309-0    5059.0   circle   80  340         0         529        0
12    14309-0    5059.0   circle   80  340         0         529        1
13    14309-0    5236.0   circle  152  284         0         177        0
14    14309-0    5236.0   circle  152  284         0         177        1
15    14309-0    5412.0   circle   64  252         0         176        0
16    14309-0    5412.0   circle   64  252         0         176        1
17    14309-0    5589.0   circle  136  192         0         177        0
18    14309-0    5589.0   circle  136  192         0         177        1
19    14309-0    5677.0   circle  136  192         0          88        0
20    14309-0    5677.0   circle  136  192         0          88        1
21    14309-0    5765.0   circle  136  192         0          88        0
22    14309-0    5765.0   circle  136  192         0          88        1
23    14309-0    5853.0   circle  136  192         0          88        0
24    14309-0    5853.0   circle  136  192         0          88        1
25    14309-0    5942.0   circle  136  192         0          89        0
26    14309-0    5942.0   circle  136  192         0          89        1
27    14309-0    6294.0   slider  256   44       176         352        0
28    14309-0    6294.0   slider  256   44       176         352        1
29    14309-0    7000.0   circle  316  224         0         706        0
30    14309-0    7000.0   circle  316  224         0         706        1
31    14309-0    7353.0   slider  172  112       176         353        0
32    14309-0    7353.0   slider  172  112       176         353        1
33    14309-0    7883.0   slider  340  272       176         530        0
34    14309-0    7883.0   slider  340  272       176         530        1
35    14309-0    8412.0   circle  256  192         0         529        0
36    14309-0    8412.0   circle  256  192         0         529        1
37    14309-0    8765.0   circle  376  192         0         353        0
38    14309-0    8765.0   circle  376  192         0         353        1
39    14309-0    9117.0   slider  256  340       176         352        0
40    14309-0    9117.0   slider  256  340       176         352        1
41    14309-0    9824.0   circle  256  192         0         707        0
42    14309-0    9824.0   circle  256  192         0         707        1
43    14309-0   10000.0   circle  256  192         0         176        1
44    14309-0   10177.0   circle  256   96         0         177        1
45    14309-0   10177.0   circle  256   96         0         177        2
46    14309-0   10353.0   circle  160  192         0         176        1
47    14309-0   10353.0   circle  160  192         0         176        2
48    14309-0   10530.0   circle  256  288         0         177        1
49    14309-0   10530.0   circle  256  288         0         177        2
50    14309-0   10706.0   circle  352  192         0         176        1
51    14309-0   10706.0   circle  352  192         0         176        2
52    14309-0   10883.0   circle  336   96         0         177        1
53    14309-0   10883.0   circle  336   96         0         177        2
54    14309-0   10971.0   circle  316   84         0          88        1
55    14309-0   10971.0   circle  316   84         0          88        2
56    14309-0   11059.0   circle  292   76         0          88        1
57    14309-0   11059.0   circle  292   76         0          88        2
58    14309-0   11147.0   circle  268   72         0          88        1
59    14309-0   11147.0   circle  268   72         0          88        2
60    14309-0   11236.0   circle  244   72         0          89        1
61    14309-0   11236.0   circle  244   72         0          89        2
62    14309-0   11324.0   circle  220   76         0          88        1
63    14309-0   11324.0   circle  220   76         0          88        2
64    14309-0   11412.0   circle  200   84         0          88        1
65    14309-0   11412.0   circle  200   84         0          88        2
66    14309-0   11500.0   circle  180   96         0          88        1
67    14309-0   11500.0   circle  180   96         0          88        2
68    14309-0   11589.0   slider  164  112       352          89        1
69    14309-0   11589.0   slider  164  112       352          89        2
70    14309-0   12118.0   slider  272  312       176         529        1
71    14309-0   12118.0   slider  272  312       176         529        2
72    14309-0   12471.0   slider  280  216       176         353        1
73    14309-0   12471.0   slider  280  216       176         353        2
74    14309-0   13000.0   slider  272  312       176         529        1
75    14309-0   13000.0   slider  272  312       176         529        2
76    14309-0   13353.0   slider  192  164       176         353        1
77    14309-0   13353.0   slider  192  164       176         353        2
78    14309-0   13706.0   circle   48  148         0         353        1
79    14309-0   13706.0   circle   48  148         0         353        2
80    14309-0   13794.0   circle   52  172         0          88        1
81    14309-0   13794.0   circle   52  172         0          88        2
82    14309-0   13883.0   circle   64  192         0          89        1
83    14309-0   13883.0   circle   64  192         0          89        2
84    14309-0   14059.0   slider  124  264       176         176        1
85    14309-0   14059.0   slider  124  264       176         176        2
86    14309-0   14412.0   slider  304  304       176         353        1
87    14309-0   14412.0   slider  304  304       176         353        2
88    14309-0   14765.0   circle  381  249         0         353        1
89    14309-0   14765.0   circle  381  249         0         353        2
90    14309-0   14942.0   circle  380  156         0         177        1
91    14309-0   14942.0   circle  380  156         0         177        2
92    14309-0   15118.0   slider  380  156       176         176        2
93    14309-0   15118.0   slider  380  156       176         176        3
94    14309-0   15471.0   slider  216  248       176         353        2
95    14309-0   15471.0   slider  216  248       176         353        3
96    14309-0   15824.0   circle  144  100         0         353        2
97    14309-0   15824.0   circle  144  100         0         353        3
98    14309-0   15912.0   circle  160   84         0          88        2
99    14309-0   15912.0   circle  160   84         0          88        3
100   14309-0   16000.0   circle  180   76         0          88        2
101   14309-0   16000.0   circle  180   76         0          88        3
102   14309-0   16089.0   circle  204   72         0          89        2
103   14309-0   16089.0   circle  204   72         0          89        3
104   14309-0   16177.0   circle  228   72         0          88        2
105   14309-0   16177.0   circle  228   72         0          88        3
106   14309-0   16353.0   slider  320  100       176         176        2
107   14309-0   16353.0   slider  320  100       176         176        3
108   14309-0   16706.0   circle  372   28         0         353        2
109   14309-0   16706.0   circle  372   28         0         353        3
110   14309-0   16883.0   slider  352  192       176         177        2
111   14309-0   16883.0   slider  352  192       176         177        3
112   14309-0   17236.0   circle  184  216         0         353        2
113   14309-0   17236.0   circle  184  216         0         353        3
114   14309-0   17412.0   circle  124  288         0         176        2
115   14309-0   17412.0   circle  124  288         0         176        3
116   14309-0   17500.0   circle  140  304         0          88        2
117   14309-0   17500.0   circle  140  304         0          88        3
118   14309-0   17589.0   circle  164  312         0          89        2
119   14309-0   17589.0   circle  164  312         0          89        3
120   14309-0   17765.0   slider  256  340       176         176        2
121   14309-0   17765.0   slider  256  340       176         176        3
122   14309-0   18118.0   slider  280  192       176         353        2
123   14309-0   18118.0   slider  280  192       176         353        3
124   14309-0   18647.0   circle  372  172         0         529        2
125   14309-0   18647.0   circle  372  172         0         529        3
126   14309-0   18736.0   circle  388  156         0          89        2
127   14309-0   18736.0   circle  388  156         0          89        3
128   14309-0   18824.0   circle  392  132         0          88        2
129   14309-0   18824.0   circle  392  132         0          88        3
130   14309-0   18912.0   circle  388  108         0          88        2
131   14309-0   18912.0   circle  388  108         0          88        3
132   14309-0   19000.0   circle  372   92         0          88        2
133   14309-0   19000.0   circle  372   92         0          88        3
134   14309-0   19177.0   circle  280   68         0         177        2
135   14309-0   19177.0   circle  280   68         0         177        3
136   14309-0   19353.0   slider  184   72       176         176        2
137   14309-0   19353.0   slider  184   72       176         176        3
138   14309-0   19706.0   slider  188  232       176         353        2
139   14309-0   19706.0   slider  188  232       176         353        3
140   14309-0   20059.0   slider  184   72       176         353        3
141   14309-0   20059.0   slider  184   72       176         353        4
142   14309-0   20412.0   circle  344  132         0         353        3
143   14309-0   20412.0   circle  344  132         0         353        4
144   14309-0   20589.0   circle  280   68         0         177        3
145   14309-0   20589.0   circle  280   68         0         177        4
146   14309-0   20765.0   slider  344  132       176         176        3
147   14309-0   20765.0   slider  344  132       176         176        4
148   14309-0   21118.0   slider  168  252       176         353        3
149   14309-0   21118.0   slider  168  252       176         353        4
150   14309-0   21471.0   slider  343  220       352         353        3
151   14309-0   21471.0   slider  343  220       352         353        4
152   14309-0   22000.0   circle   96  104         0         529        3
153   14309-0   22000.0   circle   96  104         0         529        4
154   14309-0   22177.0   circle   32  172         0         177        3
155   14309-0   22177.0   circle   32  172         0         177        4
156   14309-0   22265.0   circle   32  196         0          88        3
157   14309-0   22265.0   circle   32  196         0          88        4
158   14309-0   22353.0   circle   32  220         0          88        3
159   14309-0   22353.0   circle   32  220         0          88        4
160   14309-0   22530.0   circle  104  284         0         177        3
161   14309-0   22530.0   circle  104  284         0         177        4
162   14309-0   22618.0   circle  104  260         0          88        3
163   14309-0   22618.0   circle  104  260         0          88        4
164   14309-0   22706.0   circle  104  236         0          88        3
165   14309-0   22706.0   circle  104  236         0          88        4
166   14309-0   22883.0   slider  160  160       176         177        3
167   14309-0   22883.0   slider  160  160       176         177        4
168   14309-0   23236.0   slider  164  284       176         353        3
169   14309-0   23236.0   slider  164  284       176         353        4
170   14309-0   23589.0   slider  316  196       352         353        3
171   14309-0   23589.0   slider  316  196       352         353        4
172   14309-0   24471.0   circle  224  220         0         882        3
173   14309-0   24471.0   circle  224  220         0         882        4
174   14309-0   24559.0   circle  204  228         0          88        3
175   14309-0   24559.0   circle  204  228         0          88        4
176   14309-0   24647.0   circle  180  232         0          88        3
177   14309-0   24647.0   circle  180  232         0          88        4
178   14309-0   24824.0   circle   84  236         0         177        3
179   14309-0   24824.0   circle   84  236         0         177        4
180   14309-0   25000.0   slider  132  156       176         176        4
181   14309-0   25000.0   slider  132  156       176         176        5
182   14309-0   25353.0   slider  188   80       176         353        4
183   14309-0   25353.0   slider  188   80       176         353        5
184   14309-0   25706.0   circle  360   96         0         353        4
185   14309-0   25706.0   circle  360   96         0         353        5
186   14309-0   25794.0   circle  380  108         0          88        4
187   14309-0   25794.0   circle  380  108         0          88        5
188   14309-0   25883.0   slider  396  128       176          89        4
189   14309-0   25883.0   slider  396  128       176          89        5
190   14309-0   26236.0   circle  336  280         0         353        4
191   14309-0   26236.0   circle  336  280         0         353        5
192   14309-0   26412.0   slider  312  188       352         176        4
193   14309-0   26412.0   slider  312  188       352         176        5
194   14309-0   27294.0   circle  376  116         0         882        4
195   14309-0   27294.0   circle  376  116         0         882        5
196   14309-0   27383.0   circle  356  100         0          89        4
197   14309-0   27383.0   circle  356  100         0          89        5
198   14309-0   27471.0   circle  332   92         0          88        4
199   14309-0   27471.0   circle  332   92         0          88        5
200   14309-0   27647.0   circle  236   92         0         176        4
201   14309-0   27647.0   circle  236   92         0         176        5
202   14309-0   27824.0   slider  140   92       176         177        4
203   14309-0   27824.0   slider  140   92       176         177        5
204   14309-0   28177.0   slider  180  288       176         353        4
205   14309-0   28177.0   slider  180  288       176         353        5
206   14309-0   28530.0   slider  120  180       176         353        4
207   14309-0   28530.0   slider  120  180       176         353        5
208   14309-0   28794.0   circle  116  284         0         264        4
209   14309-0   28794.0   circle  116  284         0         264        5
210   14309-0   28883.0   circle  136  300         0          89        4
211   14309-0   28883.0   circle  136  300         0          89        5
212   14309-0   29059.0   circle  228  316         0         176        4
213   14309-0   29059.0   circle  228  316         0         176        5
214   14309-0   29236.0   slider  320  300       176         177        4
215   14309-0   29236.0   slider  320  300       176         177        5
216   14309-0   29589.0   slider  480  228       176         353        4
217   14309-0   29589.0   slider  480  228       176         353        5
218   14309-0   29942.0   circle  336  144         0         353        4
219   14309-0   29942.0   circle  336  144         0         353        5
220   14309-0   30030.0   circle  312  144         0          88        5
221   14309-0   30030.0   circle  312  144         0          88        6
222   14309-0   30118.0   circle  292  152         0          88        5
223   14309-0   30118.0   circle  292  152         0          88        6
224   14309-0   30294.0   slider  212  200       176         176        5
225   14309-0   30294.0   slider  212  200       176         176        6
226   14309-0   30647.0   circle   56  116         0         353        5
227   14309-0   30647.0   circle   56  116         0         353        6
228   14309-0   30824.0   circle   56  116         0         177        5
229   14309-0   30824.0   circle   56  116         0         177        6
230   14309-0   31000.0   circle  148   96         0         176        5
231   14309-0   31000.0   circle  148   96         0         176        6
232   14309-0   31177.0   circle  148   96         0         177        5
233   14309-0   31177.0   circle  148   96         0         177        6
234   14309-0   31353.0   circle  240   76         0         176        5
235   14309-0   31353.0   circle  240   76         0         176        6
236   14309-0   31442.0   circle  264   72         0          89        5
237   14309-0   31442.0   circle  264   72         0          89        6
238   14309-0   31530.0   circle  288   76         0          88        5
239   14309-0   31530.0   circle  288   76         0          88        6
240   14309-0   31706.0   circle  376  112         0         176        5
241   14309-0   31706.0   circle  376  112         0         176        6
242   14309-0   31883.0   circle  288  152         0         177        5
243   14309-0   31883.0   circle  288  152         0         177        6
244   14309-0   31971.0   circle  264  160         0          88        5
245   14309-0   31971.0   circle  264  160         0          88        6
246   14309-0   32059.0   circle  240  152         0          88        5
247   14309-0   32059.0   circle  240  152         0          88        6
248   14309-0   32236.0   slider  152  116       176         177        5
249   14309-0   32236.0   slider  152  116       176         177        6
250   14309-0   32589.0   slider  168  212       176         353        5
251   14309-0   32589.0   slider  168  212       176         353        6
252   14309-0   32942.0   slider  256  192       176         353        5
253   14309-0   32942.0   slider  256  192       176         353        6
254   14309-0   33471.0   circle  236  100         0         529        5
255   14309-0   33471.0   circle  236  100         0         529        6
256   14309-0   33559.0   circle  240   76         0          88        5
257   14309-0   33559.0   circle  240   76         0          88        6
258   14309-0   33647.0   circle  252   56         0          88        5
259   14309-0   33647.0   circle  252   56         0          88        6
260   14309-0   33736.0   circle  272   44         0          89        5
261   14309-0   33736.0   circle  272   44         0          89        6
262   14309-0   33824.0   slider  296   40       176          88        5
263   14309-0   33824.0   slider  296   40       176          88        6
264   14309-0   44059.0  spinner  256  192      1412       10235        7
265   14309-0   44059.0  spinner  256  192      1412       10235        8
266   14309-0   44059.0  spinner  256  192      1412       10235        9
267   14309-0   45824.0   circle   88  136         0        1765        8
268   14309-0   45824.0   circle   88  136         0        1765        9

In [30]:
grouped = df.groupby("id")

In [37]:
pd.options.display.max_rows = None

In [44]:
for idx, group in grouped:
    group = group.sort_values(by=["id", "chunk_id"])
    display(group[["id", "time", "type", "x", "y", "duration", "delta_time", "chunk_id", "chunk_start", "hit_start_rel", "hit_end_rel"]])
    # last_chunk_id = group.iloc[-1]["chunk_id"][-1]
    # for i in range(0, last_chunk_id + 1):
        
    break

             id    time     type    x    y  duration  delta_time chunk_id  \
0       14309-0   295.0   circle  376  192         0         295        0
1       14309-0   647.0   slider  256  340       176         352        0
2       14309-0  1353.0   circle  196  160         0         706        0
3       14309-0  1706.0   slider  340  272       176         353        0
4       14309-0  2236.0   slider  172  112       176         530        0
5       14309-0  2765.0   circle  256  192         0         529        0
6       14309-0  3118.0   circle  136  192         0         353        0
7       14309-0  3470.0   slider  256   44       176         352        0
8       14309-0  4176.0   circle  316  224         0         706        0
9       14309-0  4353.0   circle  196  224         0         177        0
10      14309-0  4530.0   slider  256  120       176         177        0
11      14309-0  5059.0   circle   80  340         0         529        0
13      14309-0  5236.0   circle  152  284         0         177        0
15      14309-0  5412.0   circle   64  252         0         176        0
17      14309-0  5589.0   circle  136  192         0         177        0
19      14309-0  5677.0   circle  136  192         0          88        0
21      14309-0  5765.0   circle  136  192         0          88        0
23      14309-0  5853.0   circle  136  192         0          88        0
25      14309-0  5942.0   circle  136  192         0          89        0
27      14309-0  6294.0   slider  256   44       176         352        0
29      14309-0  7000.0   circle  316  224         0         706        0
31      14309-0  7353.0   slider  172  112       176         353        0
33      14309-0  7883.0   slider  340  272       176         530        0
35      14309-0  8412.0   circle  256  192         0         529        0
37      14309-0  8765.0   circle  376  192         0         353        0
39      14309-0  9117.0   slider  256  340       176         352        0
41      14309-0  9824.0   circle  256  192         0         707        0
2111    14309-1   295.0   slider  344  248       352         295        0
2112    14309-1   824.0   slider  167  136       352         529        0
2113    14309-1  1353.0   circle  256  192         0         529        0
2114    14309-1  1706.0   circle  464  256         0         353        0
2115    14309-1  1883.0   circle  464  128         0         177        0
2116    14309-1  2236.0   circle  112  320         0         353        0
2117    14309-1  2412.0   circle   72  240         0         176        0
2118    14309-1  2589.0   circle   72  144         0         177        0
2119    14309-1  2765.0   circle  120   64         0         176        0
2120    14309-1  2942.0   circle  344  136         0         177        0
2121    14309-1  3030.0   circle  344  136         0          88        0
2122    14309-1  3118.0   slider  344  136       352          88        0
2123    14309-1  3647.0   slider  168  248       352         529        0
2124    14309-1  4176.0   circle  256  192         0         529        0
2125    14309-1  4353.0   circle  192  104         0         177        0
2126    14309-1  4530.0   circle  320  104         0         177        0
2127    14309-1  4706.0   circle  256   16         0         176        0
2128    14309-1  5059.0   circle  256  192         0         353        0
2130    14309-1  5236.0   circle   88  144         0         177        0
2132    14309-1  5324.0   circle   88  144         0          88        0
2134    14309-1  5412.0   circle   88  144         0          88        0
2136    14309-1  5589.0   circle  424  240         0         177        0
2138    14309-1  5677.0   circle  424  240         0          88        0
2140    14309-1  5765.0   circle  424  240         0          88        0
2142    14309-1  5942.0   slider  344  136       352         177        0
2144    14309-1  6471.0   slider  168  248       352         529        0
2146    14309-1  7000.0   circle  256  192         0         529        0
2148    14309-1  7353.0   circle   32  128         0         353        0
2150    14309-1  7530.0   circle   32  256         0         177        0
2152    14309-1  7706.0   circle  136  192         0         176        0
2154    14309-1  7883.0   circle  136  192         0         177        0
2156    14309-1  8059.0   circle  256  192         0         176        0
2158    14309-1  8236.0   circle  256  192         0         177        0
2160    14309-1  8412.0   circle  376  192         0         176        0
2162    14309-1  8589.0   circle  376  192         0         177        0
2164    14309-1  8765.0   slider  168  136       352         176        0
2166    14309-1  9294.0   slider  344  248       352         529        0
2168    14309-1  9824.0   circle  256  192         0         530        0
6146    16489-0  3042.0   slider   40  192       685        3042        0
6147    16489-0  4071.0   slider  208  152       342        1029        0
6148    16489-0  5099.0   circle  208   72         0        1028        0
6150    16489-0  5785.0   slider  472  192       685         686        0
6152    16489-0  6814.0   slider  304  152       342        1029        0
6154    16489-0  7842.0   circle  384  152         0        1028        0
6156    16489-0  8357.0   slider  256   40       171         515        0
6158    16489-0  8871.0   slider  256  144       171         514        0
6160    16489-0  9385.0   circle  256  264         0         514        0
6162    16489-0  9728.0   circle  256  344         0         343        0
6590    16489-1  3042.0   slider  128   80       685        3042        0
6591    16489-1  4071.0   circle  216  344         0        1029        0
6592    16489-1  4414.0   slider  304  264       685         343        0
6594    16489-1  5785.0   slider  448   56       685        1371        0
6596    16489-1  6814.0   circle  232  272         0        1029        0
6598    16489-1  7157.0   slider  112  240       685         343        0
6600    16489-1  8357.0   circle  368  248         0        1200        0
6602    16489-1  8528.0   slider  320  280       342         171        0
6604    16489-1  9042.0   circle  240  176         0         514        0
6606    16489-1  9385.0   circle  320   88         0         343        0
6608    16489-1  9728.0   slider  208   48       685         343        0
7046    16489-4  3042.0   slider   56  112       685        3042        0
7047    16489-4  4071.0   circle  472  192         0        1029        0
7048    16489-4  4414.0   slider  352  288       685         343        0
7050    16489-4  5785.0   circle  256   32         0        1371        0
7052    16489-4  6471.0   circle  408  288         0         686        0
7054    16489-4  6814.0   circle  256  288         0         343        0
7056    16489-4  7157.0   circle  104  288         0         343        0
7058    16489-4  7842.0   circle  256   32         0         685        0
7060    16489-4  8357.0   circle   96  192         0         515        0
7062    16489-4  8528.0   circle  184  192         0         171        0
7064    16489-4  8871.0   circle  336  192         0         343        0
7066    16489-4  9042.0   circle  424  192         0         171        0
7068    16489-4  9385.0   slider  424  344       342         343        0
9942    18779-0  3221.0   circle  400   88         0        3221        0
9943    18779-0  3405.0   slider  400   88       552         184        0
9944    18779-0  4141.0   circle  219  146         0         736        0
9945    18779-0  4510.0   circle  248  256         0         369        0
9946    18779-0  4878.0   circle  136  280         0         368        0
9947    18779-0  5246.0   circle  104  168         0         368        0
9949    18779-0  5614.0   circle  184   80         0         368        0
9951    18779-0  5798.0   slider  184   80       368         184        0
9953    18779-0  6350.0   slider  400  128       552         552        0
9955    18779-0  7086.0   circle  348  306         0         736        0
9957    18779-0  7454.0   circle  240  328         0         368        0
9959    18779-0  7822.0   circle  216  216         0         368        0
9961    18779-0  8191.0   circle  328  192         0         369        0
9963    18779-0  8559.0   circle  424  248         0         368        0
9965    18779-0  8743.0   slider  424  248       368         184        0
9967    18779-0  9295.0   slider  248  184       552         552        0
10391   18779-1  1197.0  spinner  256  192      1840        1197        0
10392   18779-1  3221.0   circle  256  192         0        2024        0
10393   18779-1  3405.0   slider  176  240       184         184        0
10394   18779-1  3957.0   circle  256  192         0         552        0
10395   18779-1  4141.0   slider  336  136       184         184        0
10396   18779-1  4694.0   circle  256  192         0         553        0
10397   18779-1  4878.0   circle  336  240         0         184        0
10398   18779-1  5062.0   circle  320  312         0         184        0
10400   18779-1  5246.0   circle  256  344         0         184        0
10402   18779-1  5430.0   circle  192  312         0         184        0
10404   18779-1  5614.0   circle  176  240         0         184        0
10406   18779-1  5798.0   slider  256  192       368         184        0
10408   18779-1  6350.0   circle  168   72         0         552        0
10410   18779-1  6534.0   circle  256   32         0         184        0
10412   18779-1  6718.0   circle  344   72         0         184        0
10414   18779-1  6902.0   circle  256  112         0         184        0
10416   18779-1  7086.0   slider  168  152       184         184        0
10418   18779-1  7454.0   slider  336  152       184         368        0
10420   18779-1  7822.0   circle  256  296         0         368        0
10422   18779-1  8007.0   slider  256  296       184         185        0
10424   18779-1  8375.0   slider  176  216       368         368        0
10426   18779-1  8927.0   slider  296  144       184         552        0
10428   18779-1  9295.0   circle  256   72         0         368        0
10430   18779-1  9479.0   circle  176   96         0         184        0
10432   18779-1  9663.0   circle  152  176         0         184        0
10434   18779-1  9847.0   circle  200  240         0         184        0
12682   20381-1  3201.0   circle  384   80         0        3201        0
12683   20381-1  3516.0   slider  384   80       315         315        0
12684   20381-1  3990.0   circle  276  120         0         474        0
12685   20381-1  4148.0   slider  204  168       473         158        0
12686   20381-1  4779.0   circle  320  260         0         631        0
12687   20381-1  5095.0   slider  320  260       315         316        0
12689   20381-1  5569.0   circle  180  236         0         474        0
12691   20381-1  5727.0   slider  108  220       315         158        0
12693   20381-1  6200.0   circle  144  364         0         473        0
12695   20381-1  6358.0   slider  144  292       473         158        0
12697   20381-1  6990.0   circle   84   96         0         632        0
12699   20381-1  7306.0   circle   84   96         0         316        0
12701   20381-1  7464.0   circle  144   56         0         158        0
12703   20381-1  7622.0   slider  212   40       157         158        0
12705   20381-1  7937.0   slider  200  120       157         315        0
12707   20381-1  8253.0   slider  316  136       315         316        0
12709   20381-1  8727.0   circle  264  280         0         474        0
12711   20381-1  8885.0   slider  228  220       473         158        0
12713   20381-1  9516.0   slider  440  120       315         631        0
12715   20381-1  9990.0   circle  392  236         0         474        0
13625   20381-2  3201.0   circle   96   48         0        3201        0
13626   20381-2  3516.0   circle   96   48         0         315        0
13627   20381-2  3674.0   circle   48  128         0         158        0
13628   20381-2  3832.0   circle   96  208         0         158        0
13629   20381-2  3990.0   circle   48  288         0         158        0
13630   20381-2  4148.0   slider   96  368       315         158        0
13631   20381-2  4622.0   slider  304  352       473         474        0
13633   20381-2  5253.0   circle  288   80         0         631        0
13635   20381-2  5411.0   circle  208  112         0         158        0
13637   20381-2  5727.0   circle   32  192         0         316        0
13639   20381-2  6043.0   circle   32  192         0         316        0
13641   20381-2  6201.0   circle  112  224         0         158        0
13643   20381-2  6358.0   circle  192  192         0         157        0
13645   20381-2  6516.0   circle  272  224         0         158        0
13647   20381-2  6674.0   slider  272  224       315         158        0
13649   20381-2  7148.0   slider  416  144       157         474        0
13651   20381-2  7464.0   slider  368   80       157         316        0
13653   20381-2  7937.0   circle  288  112         0         473        0
13655   20381-2  8253.0   slider  112   48       315         316        0
13657   20381-2  8727.0   slider   64  256       157         474        0
13659   20381-2  9043.0   circle  208  288         0         316        0
13661   20381-2  9201.0   slider  288  256       473         158        0
14554   20381-3  3201.0   slider   72  192       315        3201        0
14555   20381-3  3832.0   slider  120  112       315         631        0
14556   20381-3  4464.0   slider  168   32       157         632        0
14557   20381-3  5095.0   slider  168   32       315         631        0
14559   20381-3  5727.0   slider  360   32       315         632        0
14561   20381-3  6358.0   slider  344   88       315         631        0
14563   20381-3  6990.0   slider  312  128       315         632        0
14565   20381-3  7622.0   slider  264  160       315         632        0
14567   20381-3  8253.0   slider  192  312       157         631        0
14569   20381-3  8885.0   slider  192  312       315         632        0
14571   20381-3  9516.0   slider  200  128       315         631        0
16380   22334-1  1176.0   circle   72   64         0        1176        0
16381   22334-1  1533.0   circle  240   40         0         357        0
16382   22334-1  1712.0   slider  312   80       357         179        0
16383   22334-1  2247.0   circle  336  248         0         535        0
16384   22334-1  2426.0   circle  384  184         0         179        0
16385   22334-1  2783.0   circle  384  336         0         357        0
16386   22334-1  2961.0   circle  304  344         0         178        0
16387   22334-1  3050.0   circle  296  336         0          89        0
16388   22334-1  3140.0   circle  288  328         0          90        0
16389   22334-1  3497.0   circle  120  312         0         357        0
16390   22334-1  3675.0   circle   88  232         0         178        0
16391   22334-1  3765.0   circle   64  208         0          90        0
16392   22334-1  3854.0   circle   80  176         0          89        0
16393   22334-1  3943.0   circle   96  144         0          89        0
16394   22334-1  4033.0   slider   72  120       178          90        0
16395   22334-1  4390.0   circle   22   27         0         357        0
16396   22334-1  4569.0   slider   72  120       357         179        0
16397   22334-1  5105.0   circle  344  168         0         536        0
16399   22334-1  5283.0   slider  392  232       357         178        0
16401   22334-1  6890.0   circle  392  232         0        1607        0
16403   22334-1  8319.0   circle  118  323         0        1429        0
16405   22334-1  8676.0   circle   24  184         0         357        0
16407   22334-1  8855.0   slider  104  200       178         179        0
16409   22334-1  9390.0   circle  256   24         0         535        0
16411   22334-1  9569.0   circle  256  104         0         179        0
16413   22334-1  9748.0   circle  256  184         0         179        0
17315   22334-2   462.0   slider  256   96       535         462        0
17316   22334-2  1176.0   circle  395   89         0         714        0
17317   22334-2  1712.0   slider  438  300       357         536        0
17318   22334-2  2247.0   circle  464  116         0         535        0
17319   22334-2  2426.0   circle  396   89         0         179        0
17320   22334-2  2962.0   slider  204  189       178         536        0
17321   22334-2  3497.0   slider   42  292       178         535        0
17322   22334-2  3855.0   circle  170  313         0         358        0
17323   22334-2  4033.0   slider  237  289       535         178        0
17324   22334-2  4926.0   circle  217   35         0         893        0
17325   22334-2  5105.0   circle  179   96         0         179        0
17327   22334-2  5283.0   slider  113  125       535         178        0
17329   22334-2  6890.0   circle  256  255         0        1607        0
17331   22334-2  8319.0   circle  256  256         0        1429        0
17333   22334-2  9748.0   circle  256  256         0        1429        0
17892   22334-3   462.0   slider  257   50       714         462        0
17893   22334-3  1355.0   slider  280  320        89         893        0
17894   22334-3  1712.0   slider  177  221       357         357        0
17895   22334-3  2247.0   circle  248  128         0         535        0
17896   22334-3  2426.0   slider  337   53       357         179        0
17897   22334-3  2962.0   slider  248  128       178         536        0
17898   22334-3  3498.0   slider  397  340        89         536        0
17899   22334-3  4033.0   circle  376  336         0         535        0
17900   22334-3  4212.0   circle  256  248         0         179        0
17901   22334-3  4301.0   circle  256  224         0          89        0
17902   22334-3  4390.0   circle  256  200         0          89        0
17903   22334-3  4569.0   circle  255   92         0         179        0
17904   22334-3  4926.0   circle  159  252         0         357        0
17905   22334-3  5105.0   circle  353  252         0         179        0
17907   22334-3  5283.0   circle  255   92         0         178        0
17909   22334-3  5373.0  spinner  256  192      2946          90        0
17911   22334-3  8855.0   slider  256   88       357        3482        0
17913   22334-3  9390.0   circle   58  204         0         535        0
17915   22334-3  9747.0   circle  256  176         0         357        0
19158   22509-1   731.0   slider   96   96       157         731        0
19159   22509-1  1047.0   circle  208   56         0         316        0
19160   22509-1  1205.0   circle  248   96         0         158        0
19161   22509-1  1363.0   slider  248  152       157         158        0
19162   22509-1  1837.0   slider  248   96       315         474        0
19163   22509-1  2310.0   circle  376  112         0         473        0
19164   22509-1  2468.0   circle  336  152         0         158        0
19165   22509-1  2626.0   slider  368  200       157         158        0
19166   22509-1  3258.0   slider  400  320       157         632        0
19167   22509-1  3574.0   circle  280  344         0         316        0
19168   22509-1  3732.0   circle  232  320         0         158        0
19169   22509-1  3889.0   slider  216  264       157         157        0
19170   22509-1  4363.0   slider  184  312       315         474        0
19171   22509-1  4837.0   circle   88  296         0         474        0
19172   22509-1  4995.0   circle   56  248         0         158        0