In [129]:
import pandas as pd

df = pd.read_csv("/home/saliherdemk/try_dataset/formatted.csv")

In [130]:
CHUNK_LENGTH_SEC = 10
STEP_LENGTH_SEC = 5
SR = 16000
N_FFT = 256
HOP_LENGTH = 320
N_MELS = 64

beatmap_id = "18779-0"
chunk_start = 100000
chunk_end=110000

In [131]:
import numpy as np
df = df[
    (df["id"] == beatmap_id)
    & (df["time"] >= chunk_start)
    & (df["time"] <= chunk_end)
]
df = df.copy()

num_frames = int(((CHUNK_LENGTH_SEC * SR) - N_FFT) / HOP_LENGTH) + 1
frame_duration = (chunk_end - chunk_start) / num_frames

frame_starts = chunk_start + np.arange(num_frames) * frame_duration
frame_ends = frame_starts + frame_duration

In [132]:
df

,id,time,type,x,y,hit_sound,path,repeat,spinner_time,new_combo,...,effects,difficulty_rating,meter,beat_length,mapper_id,beatmap_id,duration,delta_time,duration_tick,delta_time_tick
224,18779-0,100583.0,spinner,256,192,4,E|,0,106473,True,...,1,2.88,4,368.09816,73453,18779,5890,1472,64,16

In [133]:
is_circle = np.zeros(num_frames, dtype=float)
is_slider_start = np.zeros(num_frames, dtype=float)
is_slider_end = np.zeros(num_frames, dtype=float)
is_spinner_start = np.zeros(num_frames, dtype=float)
is_spinner_end = np.zeros(num_frames, dtype=float)
start_offset = np.zeros(num_frames, dtype=float)
end_offset = np.zeros(num_frames, dtype=float)

result_df = pd.DataFrame({
    "start": frame_starts,
    "end": frame_ends,
    "is_circle": 0,
    "is_slider_start": 0,
    "is_slider_end": 0,
    "is_spinner_start": 0,
    "is_spinner_end": 0,
    "start_offset": 0,
    "end_offset": 0,
})

In [134]:
df["end"] = df["time"] + df["duration"]

for i, row in result_df.iterrows():
    start, end = row["start"], row["end"]

    hit_start_in_frame = df[(df["time"] >= start) & (df["time"] < end)]
    hit_end_in_frame = df[(df["end"] >= start) & (df["end"] < end)]

    total_hits_in_frame = pd.concat([hit_start_in_frame, hit_end_in_frame]).drop_duplicates()
    if len(total_hits_in_frame) > 1:
        raise ValueError(f"Multiple hit objects found in frame {i}: {total_hits_in_frame}")

    if not hit_start_in_frame.empty:
        hit_type = hit_start_in_frame.iloc[0]["type"]

        if hit_type == "circle":
            result_df.at[i, "is_circle"] = 1
        elif hit_type == "slider":
            result_df.at[i, "is_slider_start"] = 1
        elif hit_type == "spinner":
            result_df.at[i, "is_spinner_start"] = 1
        result_df.at[i, "start_offset"] = hit_start_in_frame.iloc[0]["time"] - start

    if not hit_end_in_frame.empty:
        hit_type = hit_end_in_frame.iloc[0]["type"]

        if hit_type == "slider":
            result_df.at[i, "is_slider_end"] = 1
            result_df.at[i, "end_offset"] = hit_end_in_frame.iloc[0]["end"] - start

        elif hit_type == "spinner":
            result_df.at[i, "is_spinner_end"] = 1
            result_df.at[i, "end_offset"] = hit_end_in_frame.iloc[0]["end"] - start

In [137]:
result_df[result_df["is_spinner_end"] == 1]

,start,end,is_circle,is_slider_start,is_slider_end,is_spinner_start,is_spinner_end,start_offset,end_offset
323,106460.0,106480.0,0,0,0,0,1,0,13

In [138]:
df

,id,time,type,x,y,hit_sound,path,repeat,spinner_time,new_combo,...,difficulty_rating,meter,beat_length,mapper_id,beatmap_id,duration,delta_time,duration_tick,delta_time_tick,end
224,18779-0,100583.0,spinner,256,192,4,E|,0,106473,True,...,2.88,4,368.09816,73453,18779,5890,1472,64,16,106473.0